package client.demo.model;

public class SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.id
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.option_key
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    private String optionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.option_value
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    private String optionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.enable
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_config.remark
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.id
     *
     * @return the value of t_sys_config.id
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.id
     *
     * @param id the value for t_sys_config.id
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.option_key
     *
     * @return the value of t_sys_config.option_key
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public String getOptionKey() {
        return optionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.option_key
     *
     * @param optionKey the value for t_sys_config.option_key
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public void setOptionKey(String optionKey) {
        this.optionKey = optionKey == null ? null : optionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.option_value
     *
     * @return the value of t_sys_config.option_value
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.option_value
     *
     * @param optionValue the value for t_sys_config.option_value
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue == null ? null : optionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.enable
     *
     * @return the value of t_sys_config.enable
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.enable
     *
     * @param enable the value for t_sys_config.enable
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_config.remark
     *
     * @return the value of t_sys_config.remark
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_config.remark
     *
     * @param remark the value for t_sys_config.remark
     *
     * @mbggenerated Sat Mar 19 21:51:07 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}